version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: matheus
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: contactsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - monitoring_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matheus -d contactsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: matheus@email.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monitoring_network

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=contactsdb;User Id=matheus;Password=123456;
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monitoring_network
    labels:
      - "prometheus-job=api"

  angular:
    build:
      context: ./regional-contacts-app
      dockerfile: Dockerfile.angular
    ports:
      - "4200:80"
    depends_on:
      api:
        condition: service_started
    networks:
      - monitoring_network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://matheus:123456@db:5432/contactsdb?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monitoring_network

volumes:
  pgdata:

networks:
  monitoring_network:
    external: true
