services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: matheus
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: contactsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - monitoring_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: matheus@email.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - monitoring_network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://matheus:123456@db:5432/contactsdb?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - monitoring_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - monitoring_network

volumes:
  pgdata:

networks:
  monitoring_network:
    external: true
