version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: matheus
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: contactsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - monitoring_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: matheus@email.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - monitoring_network

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=contactsdb;User Id=matheus;Password=123456;
    ports:
      - "5000:8080"  
    depends_on:
      - db
    networks:
      - monitoring_network
    labels:
      - "prometheus-job=api"

  angular:
    build:
      context: ./regional-contacts-app
      dockerfile: Dockerfile.angular
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - monitoring_network

volumes:
  pgdata:

networks:
  monitoring_network:
    external: true
