apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql:latest
        ports:
        - containerPort: 8080
        env:
        - name: ZBX_SERVER_HOST
          value: "zabbix-server"
        - name: DB_SERVER_HOST
          value: "zabbix-db"
        - name: POSTGRES_USER
          value: "zabbix"
        - name: POSTGRES_PASSWORD
          value: "zabbixpass"
        - name: POSTGRES_DB
          value: "zabbix"
        volumeMounts:
        - name: zabbix-web-data
          mountPath: /var/lib/zabbix
      volumes:
      - name: zabbix-web-data
        persistentVolumeClaim:
          claimName: zabbix-web-pvc
