apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql:latest
        ports:
        - containerPort: 10051
        env:
        - name: DB_SERVER_HOST
          value: "zabbix-db"
        - name: POSTGRES_USER
          value: "zabbix"
        - name: POSTGRES_PASSWORD
          value: "zabbixpass"
        - name: POSTGRES_DB
          value: "zabbix"
        volumeMounts:
        - name: zabbix-server-data
          mountPath: /var/lib/zabbix
      volumes:
      - name: zabbix-server-data
        persistentVolumeClaim:
          claimName: zabbix-server-pvc
