name: CI/CD Pipeline AuthService.API

on:
  push:
    branches:
      - feature/criar-deploy-microservices
    paths:
      - 'api/AuthService.API/**'
  pull_request:
    branches:
      - feature/criar-deploy-microservices
    paths:
      - 'api/AuthService.API/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: matheus
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: authdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U matheus -d authdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v2

    - name: Configurar .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Esperar pelo Postgres
      run: |
        until pg_isready -h localhost -p 5432 -U matheus; do
          echo "Esperando pelo Postgres..."; 
          sleep 5;
        done

    - name: Inicializar banco de dados
      run: |
        chmod +x initialize_db.sh
        ./initialize_db.sh

    - name: Restaurar dependências para AuthService.API
      run: dotnet restore api/AuthService.API/AuthService.API.csproj

    - name: Compilar AuthService.API
      run: dotnet build api/AuthService.API/AuthService.API.csproj --no-restore --configuration Release

    - name: Executar testes unitários para AuthService.API
      run: |
        dotnet test api/AuthService.API/AuthService.API.Tests/AuthService.API.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults/UnitTests

  build:
    needs: test
    runs-on: self-hosted

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v2

    - name: Criar diretório para o repositório, se não existir
      run: |
        if not exist C:\projects\fiap mkdir C:\projects\fiap
      shell: cmd

    - name: Transferir repositório para o diretório local
      run: |
        xcopy . C:\projects\fiap /E /I /Y
      shell: cmd

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Construir imagem Docker para AuthService.API
      run: |
        cd C:\projects\fiap
        docker build --no-cache --pull -t authservice:latest -f ./api/AuthService.API/Dockerfile.api ./api/AuthService.API
      shell: cmd

    - name: Limpar cache do Docker
      run: docker builder prune -f
      shell: cmd

    - name: Limpar sistema Docker
      run: docker system prune -af --volumes
      shell: cmd

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Fazer deploy localmente
      run: |
        cd C:\projects\fiap
        docker-compose down
        docker-compose build --no-cache
        docker-compose up -d
      shell: cmd
