name: CI/CD Pipeline Infraestrutura de Serviços

on:
  push:
    branches:
      - feature/criar-deploy-microservices
    paths:
      - 'docker-compose.services.yml'    # Acionado quando este arquivo mudar
      - 'start.ps1'                      # Acionado quando este arquivo mudar
      - '.github/workflows/infra-services.yml'  # Acionado quando o próprio workflow mudar
  pull_request:
    branches:
      - feature/criar-deploy-microservices
    paths:
      - 'docker-compose.services.yml'
      - 'start.ps1'
      - '.github/workflows/infra-services.yml'

jobs:
  infra:
    runs-on: self-hosted  

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v2

      - name: Verificar versão do Docker
        run: docker --version
        shell: cmd

      - name: Verificar status do Docker
        run: docker info
        shell: cmd

      - name: Criar rede do Docker, se não existir
        run: docker network create monitoring_network || true
        shell: cmd

      - name: Subir Infraestrutura (Postgres, RabbitMQ, PgAdmin)
        run: docker-compose -f docker-compose.services.yml up --build -d
        shell: cmd

      - name: Limpar containers Docker após o job
        if: always()
        run: docker-compose -f docker-compose.services.yml down
        shell: cmd
