name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker images
      run: |
        docker build -t api:latest -f api/Dockerfile.api ./api
        docker build -t angular:latest -f regional-contacts-app/Dockerfile.angular ./regional-contacts-app

    - name: Save Docker images to tar files
      run: |
        docker save api:latest -o api.tar
        docker save angular:latest -o angular.tar

    - name: Set permissions for tar files
      run: |
        chmod 644 api.tar
        chmod 644 angular.tar

    - name: Transfer Docker images to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "*.tar"
        target: "~/projects/fiap/"

    - name: Transfer project files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "~/projects/fiap/"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/projects/fiap
          docker load -i api.tar
          docker load -i angular.tar
          docker-compose down
          docker-compose up -d
