name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar para deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker images
      run: |
        docker build -t api:latest -f ./api/Dockerfile.api .
        docker build -t angular:latest -f ./regional-contacts-app/Dockerfile.angular .

    - name: Save Docker images to tar files
      run: |
        docker save api:latest -o api.tar
        docker save angular:latest -o angular.tar

    - name: Create SSH key file
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      shell: bash

    - name: Set permissions for SSH key file
      run: chmod 600 ~/.ssh/id_rsa
      shell: bash

    - name: Transfer Docker images to server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key_path: ~/.ssh/id_rsa
        source: "*.tar"
        target: "~/projects/fiap/"

    - name: Transfer project files to server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key_path: ~/.ssh/id_rsa
        source: "."
        target: "~/projects/fiap/"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH key file
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      shell: bash

    - name: Set permissions for SSH key file
      run: chmod 600 ~/.ssh/id_rsa
      shell: bash

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ~/projects/fiap
          docker load -i api.tar
          docker load -i angular.tar
          docker-compose down
          docker-compose up -d
        EOF
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
